site_name: Generic Radial Menu - Documentation

nav:
    - Home: index.md
    - Getting Started:
        - Setting Up Input: 1setting_up_input.md
        - Creating a menu with a radial menu: 2creating_first_widget.md
        - Adding widgets to the Radial Menu: 3adding_icons.md
        - Radial Menu Settings: 4radialmenu_settings.md
    - Misc:
        - Setting a Player Controller: setting_player_controller.md
theme: readthedocs