site_name: Generic Radial Menu - Documentation

pages:
    - Home: index.md
    - Getting Started:
        - Setting Up Input: GettingStarted/Setting_up_Input.md
        - Creating a menu with a Radial Menu: GettingStarted/Creating_a_menu_with_a_Radial_Menu.md
        - Adding widgets to the Radial Menu: GettingStarted/Adding_widgets_to_the_Radial_Menu.md
        - Radial Menu Settings: GettingStarted/RadialMenuSettings.md
    - Misc:
        - Setting a Player Controller: Misc/HowToAssignA_PlayerController.md
    - Expanding The Templates:
        - Using the Multi Menu Template: ExpandingTheTemplates/UsingTheBuildTemplate.md
        - Setting up the Category Tables: ExpandingTheTemplates/SettingUpTheBuildTables.md
        - Multi Menu Template Events: ExpandingTheTemplates/MultiMenuEvents.md
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - django
